# Generated by Django 2.1.2 on 2019-02-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=255, verbose_name='author')),
                ('text', models.CharField(default='', max_length=255, verbose_name='text')),
            ],
        ),
    ]
